# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Rfc2544Test
# label used for menu selection
label: rfc_2544_skillet
description: This skillet configures a firewall to run the rfc2544 test on it

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: panos
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - RFC2544

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: ingress
    description: Ingress Interface 184.1.1.1/24
    default: Ethernet 1/5
    type_hint: dropdown
    dd_list:
      - key: ethernet1/1
        value: ethernet1/1
      - key: ethernet1/2
        value: ethernet1/2
      - key: ethernet1/3
        value: ethernet1/3
      - key: ethernet1/4
        value: ethernet1/4
      - key: ethernet1/5
        value: ethernet1/5
      - key: ethernet1/6
        value: ethernet1/6
  - name: egress
    description: Egress Interface 185.1.1.1/24
    default: Ethernet 1/6
    type_hint: dropdown
    dd_list:
      - key: ethernet1/1
        value: ethernet1/1
      - key: ethernet1/2
        value: ethernet1/2
      - key: ethernet1/3
        value: ethernet1/3
      - key: ethernet1/4
        value: ethernet1/4
      - key: ethernet1/5
        value: ethernet1/5
      - key: ethernet1/6
        value: ethernet1/6
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
# NOTE: The following snippets are auto-generated and ordered automatically.
# Changing the content of the snippet may be necessary, but do NOT change the order

# There is a variable called snippets that we can use to auto-generate this section for us
snippets:
  - name: entry-40210
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface/ethernet
    element: |-
        <entry name="{{ ingress }}">
                      <layer3>
                        <ipv6>
                          <neighbor-discovery>
                            <router-advertisement>
                              <enable>no</enable>
                            </router-advertisement>
                          </neighbor-discovery>
                        </ipv6>
                        <ndp-proxy>
                          <enabled>no</enabled>
                        </ndp-proxy>
                        <ip>
                          <entry name="184.1.1.1/24"/>
                        </ip>
                        <lldp>
                          <enable>no</enable>
                        </lldp>
                      </layer3>
                    </entry>

  - name: entry-663203
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/interface/ethernet
    element: |-
        <entry name="{{ egress }}">
                      <layer3>
                        <ipv6>
                          <neighbor-discovery>
                            <router-advertisement>
                              <enable>no</enable>
                            </router-advertisement>
                          </neighbor-discovery>
                        </ipv6>
                        <ndp-proxy>
                          <enabled>no</enabled>
                        </ndp-proxy>
                        <ip>
                          <entry name="185.1.1.1/24"/>
                        </ip>
                        <lldp>
                          <enable>no</enable>
                        </lldp>
                      </layer3>
                    </entry>

  - name: member-246076
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/import/network/interface
    element: |-
        <member>{{ ingress }}</member>

  - name: member-370574
    xpath: /config/devices/entry[@name="localhost.localdomain"]/vsys/entry[@name="vsys1"]/import/network/interface
    element: |-
        <member>{{ egress }}</member>

  - name: member-331136
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]/interface
    element: |-
        <member>{{ ingress }}</member>

  - name: member-628582
    xpath: /config/devices/entry[@name="localhost.localdomain"]/network/virtual-router/entry[@name="default"]/interface
    element: |-
        <member>{{ egress }}</member>
